name: Docker
on:
  push:
    tags:
      - 'v[0-9]+*'
  schedule:
    # twice a month
    - cron: '25 10 10,25 * *'
  workflow_dispatch:

permissions:
  attestations: write
  id-token: write
  packages: write

jobs:
  mini-ndn:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: mini-ndn
